- name: Add "{{ front.name }}" front ufw allow rules
  community.general.ufw:
    rule: allow
    direction: in
    from_ip: "{{ item }}"
    to_port: "{{ front.bind_port }}"
    state: enabled
  loop: "{{ front.firewall_allow }}"
